services:

  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - patient-service-db:/var/lib/postgresql/data
    ports:
      - "5000:5432"
    networks:
      - internal

  auth-service-db:
    image: postgres:latest
    container_name: auth-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - auth-service-db:/var/lib/postgresql/data
    ports:
      - "5001:5432"
    networks:
      - internal

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
    ports:
      - "9092:9092"
      - "9094:9094"
    depends_on:
      - patient-service
    networks:
      - internal

  patient-service:
    image: patient-service:latest
    container_name: patient-service
    build:
      context: ./patient_service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "4000:4000"
    depends_on:
      - patient-service-db
    networks:
      - internal

  billing-service:
    image: billing-service:latest
    container_name: billing-service
    build:
      context: ./billing_service
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
      - "9001:9001"
    networks:
      - internal

  analytics-service:
    image: analytics-service:latest
    container_name: analytics-service
    build:
      context: ./analytics_service
      dockerfile: Dockerfile
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "4002:4002"
    networks:
      - internal

  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    environment:
      AUTH_SERVICE_URL: http://auth-service:4005
    ports:
      - "4004:4004"
    networks:
      - internal

  auth-service:
    image: auth-service:latest
    container_name: auth-service
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      JWT_SECRET: ba4f22a6f0759f8e96cd624a9010d4e73a76591eba1276213671403ba518fa60
    ports:
      - "4005:4005"
    depends_on:
      - auth-service-db
    networks:
      - internal

volumes:
  patient-service-db:
    driver: local
    name: patient-service-db
  auth-service-db:
    driver: local
    name: auth-service-db

networks:
  internal:
    driver: bridge
    name: internal